services:
  api:
    build: .
    ports:
      - "8080:8080"
    command: bash -c "uvicorn app.api:app
      --log-config ./logging.ini
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - ./app:/home/code/app
      - ./worker-data:/worker-data
    environment:
      FAUST_BROKER_URL: "kafka://kafka:29092"
      APP_DATADIR: "/worker-data"
      APP_TABLEDIR: "/worker-data"
    depends_on:
      - kafka

  worker:
    build: .
    command: bash -c "python -m app.worker worker -l info "
    volumes:
      - ./app:/home/code/app
      - ./worker-data:/worker-data
    environment:
      FAUST_BROKER_URL: "kafka://kafka:29092"
      APP_DATADIR: "/worker-data"
      APP_TABLEDIR: "/worker-data"
    depends_on:
      - kafka
      - api

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-secrets:/etc/kafka/secrets
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: WARN
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
      - zookeeper-secrets:/etc/zookeeper/secrets

volumes:
  kafka-data: { }
  kafka-secrets: { }
  zookeeper-data: { }
  zookeeper-log: { }
  zookeeper-secrets: { }
